In [49]:
import pandas as pd
import numpy as np

df = pd.read_csv("GasPricesinBrazil_2004-2019_clean.csv", sep=",")
# df.info()
df.head(2)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.110,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.0500,0.115,5,2004

In [50]:
# df.groupby(["REGIÃO"]).describe() # Too extensive.
df.groupby(["REGIÃO"])["PREÇO MÉDIO REVENDA"].describe()
# df.groupby(["REGIÃO"])["PREÇO MÉDIO REVENDA"].sum().to_frame()

,count,mean,std,min,25%,50%,75%,max
REGIÃO,,,,,,,,
CENTRO OESTE,15429.0,11.843486,19.604109,1.097,2.101,2.7530,3.77600,99.357
NORDESTE,36869.0,10.097994,16.458280,0.975,1.988,2.6430,3.64100,79.630
NORTE,24702.0,12.670958,19.686074,1.219,2.367,2.9930,4.23000,87.270
SUDESTE,17047.0,9.700178,16.171877,0.766,1.879,2.5460,3.54750,79.192
SUL,12776.0,10.007542,16.714582,0.922,1.977,2.5765,3.51125,72.088

In [60]:
# df.groupby(["REGIÃO","PRODUTO"])["PREÇO MÉDIO REVENDA"].sum().head(12).to_frame()
df.groupby(["REGIÃO","PRODUTO"])["PREÇO MÉDIO REVENDA"].describe().head(12)

                                count       mean        std     min     25%  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  3140.0   2.135950   0.561154   1.162   1.716
             GASOLINA COMUM    3140.0   3.078123   0.616315   1.936   2.668
             GLP               3137.0  48.181149  15.189152  28.791  37.340
             GNV               1523.0   2.004153   0.457802   1.097   1.599
             ÓLEO DIESEL       3140.0   2.481534   0.627607   1.435   2.033
             ÓLEO DIESEL S10   1349.0   3.241185   0.433797   2.212   2.820
NORDESTE     ETANOL HIDRATADO  7064.0   2.322075   0.605121   1.181   1.825
             GASOLINA COMUM    7065.0   3.002337   0.641163   1.949   2.584
             GLP               7061.0  42.221312  11.654978  28.367  33.598
             GNV               5575.0   1.925318   0.555183   0.975   1.603
             ÓLEO DIESEL       7065.0   2.347550   0.606381   1.313   1.900
             ÓLEO DIESEL S10   3039.0   3.041957   0.442555   2.130   2.600

                                   50%       75%     max
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   2.0010   2.47900   3.999
             GASOLINA COMUM     2.8560   3.46025   4.963
             GLP               42.8570  55.90500  99.357
             GNV                1.9550   2.35250   3.890
             ÓLEO DIESEL        2.2455   3.01900   4.162
             ÓLEO DIESEL S10    3.2640   3.58400   4.200
NORDESTE     ETANOL HIDRATADO   2.1880   2.67550   3.927
             GASOLINA COMUM     2.7420   3.42500   4.951
             GLP               37.5750  48.18300  79.630
             GNV                1.8210   2.16850   3.811
             ÓLEO DIESEL        2.0820   2.87300   4.114
             ÓLEO DIESEL S10    3.0870   3.33800   4.069

In [61]:
groupby = df.groupby(["REGIÃO", "PRODUTO"])

# groupby.mean() # TypeError: agg function failed [how->mean,dtype->object]
# groupby.agg(["sum","min"]).head(10) # It also sums strings if you don't specify only numeric attributes.

groupby.agg({"PREÇO MÉDIO REVENDA":"mean", "NÚMERO DE POSTOS PESQUISADOS":"sum"}).head(12)

                               PREÇO MÉDIO REVENDA  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO             2.135950
             GASOLINA COMUM               3.078123
             GLP                         48.181149
             GNV                          2.004153
             ÓLEO DIESEL                  2.481534
             ÓLEO DIESEL S10              3.241185
NORDESTE     ETANOL HIDRATADO             2.322075
             GASOLINA COMUM               3.002337
             GLP                         42.221312
             GNV                          1.925318
             ÓLEO DIESEL                  2.347550
             ÓLEO DIESEL S10              3.041957

                               NÚMERO DE POSTOS PESQUISADOS
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO                        486645
             GASOLINA COMUM                          487343
             GLP                                     629342
             GNV                                       4387
             ÓLEO DIESEL                             413677
             ÓLEO DIESEL S10                          96452
NORDESTE     ETANOL HIDRATADO                       1086846
             GASOLINA COMUM                         1229333
             GLP                                     890927
             GNV                                      93211
             ÓLEO DIESEL                             957061
             ÓLEO DIESEL S10                         284675

In [39]:
def str_size_comparator(x):
    print(type(x)) # <class 'pandas.core.series.Series'>
    return x.str.len()

groupby = df.groupby(["REGIÃO", "PRODUTO"])
partial = groupby.agg({"PREÇO MÉDIO REVENDA":"mean", "NÚMERO DE POSTOS PESQUISADOS":"sum"})

partial.sort_values(by=["REGIÃO", "PRODUTO"], key=lambda x: x.str.len(), ascending=[False, True])
# partial.sort_values(by=["REGIÃO", "PRODUTO"], key=str_size_comparator, ascending=[False, True])

                               PREÇO MÉDIO REVENDA  \
REGIÃO       PRODUTO
CENTRO OESTE GLP                         48.181149
             GNV                          2.004153
             ÓLEO DIESEL                  2.481534
             GASOLINA COMUM               3.078123
             ÓLEO DIESEL S10              3.241185
             ETANOL HIDRATADO             2.135950
NORDESTE     GLP                         42.221312
             GNV                          1.925318
             ÓLEO DIESEL                  2.347550
             GASOLINA COMUM               3.002337
             ÓLEO DIESEL S10              3.041957
             ETANOL HIDRATADO             2.322075
SUDESTE      GLP                         42.077813
             GNV                          1.779684
             ÓLEO DIESEL                  2.339699
             GASOLINA COMUM               3.000565
             ÓLEO DIESEL S10              3.054425
             ETANOL HIDRATADO             2.164832
NORTE        GLP                         47.174539
             GNV                          2.000190
             ÓLEO DIESEL                  2.569905
             GASOLINA COMUM               3.149212
             ÓLEO DIESEL S10              3.310619
             ETANOL HIDRATADO             2.530796
SUL          GLP                         43.535465
             GNV                          1.907944
             ÓLEO DIESEL                  2.332862
             GASOLINA COMUM               2.973136
             ÓLEO DIESEL S10              2.981745
             ETANOL HIDRATADO             2.268864

                               NÚMERO DE POSTOS PESQUISADOS
REGIÃO       PRODUTO
CENTRO OESTE GLP                                     629342
             GNV                                       4387
             ÓLEO DIESEL                             413677
             GASOLINA COMUM                          487343
             ÓLEO DIESEL S10                          96452
             ETANOL HIDRATADO                        486645
NORDESTE     GLP                                     890927
             GNV                                      93211
             ÓLEO DIESEL                             957061
             GASOLINA COMUM                         1229333
             ÓLEO DIESEL S10                         284675
             ETANOL HIDRATADO                       1086846
SUDESTE      GLP                                    2375207
             GNV                                     234587
             ÓLEO DIESEL                            2421885
             GASOLINA COMUM                         3302995
             ÓLEO DIESEL S10                         566245
             ETANOL HIDRATADO                       3258655
NORTE        GLP                                     493669
             GNV                                        583
             ÓLEO DIESEL                             372930
             GASOLINA COMUM                          425870
             ÓLEO DIESEL S10                          94327
             ETANOL HIDRATADO                        249126
SUL          GLP                                    1143288
             GNV                                      44617
             ÓLEO DIESEL                             857264
             GASOLINA COMUM                         1167527
             ÓLEO DIESEL S10                         233078
             ETANOL HIDRATADO                       1070365